### ISSUE TITLE
Fast join

### ISSUE THREAD

**Issue by cleaton** [amplab/succinct#11]
Hello, sorry for asking this question here but I couldn't find a mailing list or similar.

Does succinct provide (or planning to provide) a faster join implementation that does not need to shuffle keys in both datasets?

I got two datasets, A and B,  where B << A (so I want to avoid sorting A) but B is not small enough to use broadcast join.
Is this a potential use case for succinct? 
Thanks

**Comment by anuragkh** [comment]
We haven't looked at join-optimizations for Succinct yet. I would point out that operations that require full scans for large compressed datasets (e.g., joins) is _not yet_ suitable for Succinct (see this [blog](https://databricks.com/blog/2015/11/10/succinct-spark-from-amplab-queries-on-compressed-rdds.html), the section on "When not to use Succinct Spark"). However, we've found that most such operations can be expressed in terms of queries that Succinct _is_ efficient for, particularly when the size of the final set of results is small. 

We are working to support efficient SQL operations for DataFrames, including joins, but we anticipate these changes only on the DataFrames side for now.

**Comment by cleaton** [comment]
Ok, Thanks for the clarification and for your work on this project. Looking forward to see where it goes in the future.
