### ISSUE TITLE
trove as a dependency with LGPL

### ISSUE THREAD

**Issue by koertkuipers** [amplab/succinct#28]
you sure an Apache 2 licensed project can depend on something that has GNU Lesser General Public License 2.1?

**Comment by koertkuipers** [comment]
see for example:
https://github.com/rubychan/coderay/issues/25

**Comment by anuragkh** [comment]
Hmm, I'm not sure; is there a workaround for this? I can try removing Trove dependencies completely in the worst case, I've slimmed down its usage considerably since the last release.

**Comment by koertkuipers** [comment]
easiest would be to convince trove to also be available under apache 2
license.

or if succinct works without trove then you could make it an optional
dependency. i don't know if this solves the license issue.

On Sun, Jun 12, 2016 at 5:59 PM, Anurag Khandelwal <notifications@github.com

**Comment by anuragkh** [comment]
Alright I'll look into it. Thanks for pointing it out!

**Comment by anuragkh** [comment]
Resolved in the master branch.
