### ISSUE TITLE
Is succinct suitable for OLAP?

### ISSUE THREAD

**Issue by flowbehappy** [amplab/succinct#36]
I am implementing a new data warehouse (https://github.com/shunfei/indexr) which is suitable for OLAP scenario. It should support fast scan, good compress ratio, and fast enough random access (ok to be slower than hbase, but not too slow). It does not need to be updatable. We group rows into files and throw to HDFS, then do queries on them. It is designed to store very large dataset, e.g. over 100TBs, but still fast enough to do ad-hoc queries.

Currently I separate the data in blocks, each block is compressed according to their data types. And index the data in block level. This design greatly reduce data size, and with the help of block level indices, random access queries is not too bad, as they can filter out most irrelevant blocks. 

The main problem now is the STRING type. Decompress process on string is too expensive. And the search queries are very slow, because they cannot take advantage of my indices(they are not designed for search). My last option is tokenizing those strings, and use an invert index, like Lucene.

Then I searched around and found Succinct. Direct queries on compressed data, naturally search support seems perfect! The benchmark looks very promising.

My questions for Succinct are:

1. Is there any improvements on the compress speed? According to this post(http://succinct.cs.berkeley.edu/wp/wordpress/) the process is a bit too slow.
2. How is the performance for scan? Scan is a every important feature for big data analyse.
3. Do you think succinct is suitable for OLAP scenario? Any suggestions for me if I decide to work on it?

Thank you for your great work!

**Comment by anuragkh** [comment]
Hi!

Great to know that you found Succinct interesting for your use case!

To answer your questions: 

1. Yes, we have added several improvements to the compression algorithm. However, compression speeds are very dataset dependent, so you should try out compressing samples of your own dataset to see if it meets your needs.

2. Sequential scans is not the best use case for Succinct. Succinct supports searches and random access pretty efficiently, but decompression rates are around ~2MB/s with a single thread. It scales linearly with the number of cores though.

3. I do think it is suitable for OLAP scenario; a lot of OLAP style queries require executing filters on huge volumes of data, which is exactly what Succinct does well. I'm happy to talk more about your use case in particular if you want.

**Comment by flowbehappy** [comment]
Thank you for your reply @anuragkh .

We are going to put Succinct on different cases and see what comes out.  I will inform you after we have some conclusions.
