### ISSUE TITLE
Is the C++ version of Succinct Open?

### ISSUE THREAD

**Issue by foudrer** [amplab/succinct#37]

**Comment by anuragkh** [comment]
No its not open sourced since it isn't completely stable/well documented; but I can provide access if you're interested. What's your use-case?

**Comment by foudrer** [comment]
Thank for your reply.  
My use-case is text search and approximate search.

**Comment by anuragkh** [comment]
The C++ version can now be found here: http://github.com/amplab/succinct-cpp
