### ISSUE TITLE
Could you share C++ version of Succinct?

### ISSUE THREAD

**Issue by jasonxcp** [amplab/succinct#40]
Hi,

I recently read the Succinct paper. I think it would be a great tool for text analysis and want to explore more use cases with Succinct. I wonder if you could share the C++ implementation for the Succinct core, so I could do more experiments?

Thanks

**Comment by anuragkh** [comment]
Hi,

Thanks for your interest in Succinct! The C++ implementation of Succinct can be found [here](http://github.com/amplab/succinct-cpp).
