### ISSUE TITLE
version 0.1.8 isn't uploaded on maven central

### ISSUE THREAD

**Issue by titsuki** [amplab/succinct#43]
Hi,
The instructions in the README recommend to use the version 0.1.8 but I found that this version isn't uploaded on maven central.
Didn't you forget to upload the version 0.1.8?

Cheers,

**Comment by anuragkh** [comment]
Hi, thanks for your interest in Succinct!

Succinct isn’t currently on Maven central unfortunately. You can either manually install succinct to your local repository:

```bash
mvn clean install
```

Or, if you’re interested in the spark plugin, you can install it from spark packages or add the spark packages sbt dependency (see readme in spark directory).

**Comment by titsuki** [comment]
@anuragkh Thanks for your reply.

> or add the spark packages sbt dependency (see readme in spark directory).

Sorry, "maven central" was incorrect expression. I mean this spark package:
http://dl.bintray.com/spark-packages/maven/amplab/succinct/

This one contains the versions up to 0.1.7 but I couldn't find the version 0.1.8.

**Comment by anuragkh** [comment]
You're right -- the latest version was not up to date in Spark Packages. I just submitted the latest version to Spark Packages, and was accepted. The jar doesn't seem to be up yet, but should be in some time. Thanks!

**Comment by titsuki** [comment]
@anuragkh It seems that 0.1.8 isn't appeared yet. Could you ensure the package uploading works fine or not again?

**Comment by anuragkh** [comment]
Its strange -- as you can see here, the package has been uploaded, but the jar isn't available: https://spark-packages.org/package/amplab/succinct.

I received a confirmation email from them as well. I will try reaching out to them regarding the jar.
