### ISSUE TITLE
Publishing to Spark Packages

### ISSUE THREAD

**Issue by brkyvz** [amplab/succinct#5]
Hi,

I noticed that you ran into several problems while publishing a release to Spark Packages. I strongly suggest that you use the [sbt-spark-package](https://github.com/databricks/sbt-spark-package) plugin, as it would greatly ease your publishing process. The Spark Packages repo has several different requirements regarding publishing, which you can find [here](http://spark-packages.org/artifact-help). Please let me know if you have any questions, and we would greatly appreciate any feedback you might have!

Thanks,
Burak

**Comment by anuragkh** [comment]
Thanks for the pointer, I'll keep track of the plugin! :)
